# Файл docker-compose.yml

# Версия docker-compose
version: '3'

# Перечень volume
volumes:
  pg_data:

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик. 
  # Это контейнер БД
  db:
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data:/var/lib/postgresql/data
  # Имя и описание контейнера с бэкендом

  migration:
    build: .
    env_file: .env
    depends_on:
      - db
    command: >
      sh -c "sleep 30 && alembic revision --autogenerate -m 'First migration' &&
              alembic upgrade head"
  backend:
    # Из какого Dockerfile собирать образ для этого контейнера:
    build: .
    env_file: .env
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db
    ports:
    - 8000:8000